version: '3.8'
services:
  db:
    image: postgres:17-alpine
    container_name: rocket-db
    restart: always
    environment:
      POSTGRES_USER: rocket
      POSTGRES_PASSWORD: rocketpassword
      POSTGRES_DB: rocket_erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: